[33mWARNING [0m juju.model:__init__.py:1683 relate is deprecated and will be removed. Use integrate instead.
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: 
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: Primary
  postgresql-test-app/0 [idle] active: 
[32mINFO    [0m integration.ha_tests.test_self_healing_2:test_self_healing_2.py:69 scaling database to zero units
[32mINFO    [0m integration.ha_tests.test_self_healing_2:test_self_healing_2.py:73 scaling database to three units
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s (waiting for exactly 3 units, current : 0)
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: installing charm software
  postgresql-k8s/1 [idle] maintenance: installing charm software
  postgresql-k8s/2 [idle] maintenance: installing charm software
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] waiting: awaiting for cluster to start
  postgresql-k8s/1 [idle] waiting: awaiting for cluster to start
  postgresql-k8s/2 [idle] waiting: awaiting for cluster to start
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] active: Primary (degraded)
  postgresql-k8s/1 [executing] active: 
  postgresql-k8s/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] active: Primary (degraded)
  postgresql-k8s/1 [executing] active: 
  postgresql-k8s/2 [executing] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] waiting: awaiting for primary endpoint to be ready
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [executing] active: Primary (degraded)
  postgresql-k8s/1 [idle] active: 
  postgresql-k8s/2 [idle] active: 
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] active: Primary (degraded)
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m juju.model:__init__.py:3254 Waiting for model:
  postgresql-k8s/0 [idle] maintenance: reconfiguring cluster
  postgresql-k8s/1 [idle] maintenance: reinitialising replica
  postgresql-k8s/2 [idle] maintenance: reinitialising replica
[32mINFO    [0m pytest_operator.plugin:plugin.py:936 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.4    unsupported  01:54:24Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
postgresql-k8s       14.17    active      3  postgresql-k8s                      0  10.152.183.219  no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  375  10.152.183.53   no       received database credentials of the first database

Unit                    Workload     Agent  Address      Ports  Message
postgresql-k8s/0*       maintenance  idle   10.1.190.79         reconfiguring cluster
postgresql-k8s/1        maintenance  idle   10.1.190.81         reinitialising replica
postgresql-k8s/2        maintenance  idle   10.1.190.80         reinitialising replica
postgresql-test-app/0*  active       idle   10.1.190.78         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:942 Juju error logs:

unit-postgresql-k8s-2: 01:38:43 ERROR unit.postgresql-k8s/2.juju-log database:4: failed to change plugins: 
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 428, in enable_disable_extensions
    with self._connect_to_database() as connection, connection.cursor() as cursor:
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 180, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgresql-k8s-primary.testing.svc.cluster.local" (10.152.183.158), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/src/charm.py", line 776, in _handle_enable_disable_extensions
    self.postgresql.enable_disable_extensions(extensions, database)
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-2/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 455, in enable_disable_extensions
    raise PostgreSQLEnableDisableExtensionError() from e
charms.postgresql_k8s.v0.postgresql.PostgreSQLEnableDisableExtensionError
unit-postgresql-k8s-1: 01:38:46 ERROR unit.postgresql-k8s/1.juju-log database:4: failed to change plugins: 
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 428, in enable_disable_extensions
    with self._connect_to_database() as connection, connection.cursor() as cursor:
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 180, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgresql-k8s-primary.testing.svc.cluster.local" (10.152.183.158), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/src/charm.py", line 776, in _handle_enable_disable_extensions
    self.postgresql.enable_disable_extensions(extensions, database)
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-1/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 455, in enable_disable_extensions
    raise PostgreSQLEnableDisableExtensionError() from e
charms.postgresql_k8s.v0.postgresql.PostgreSQLEnableDisableExtensionError
unit-postgresql-k8s-0: 01:40:09 ERROR unit.postgresql-k8s/0.juju-log failed to change plugins: 
Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 428, in enable_disable_extensions
    with self._connect_to_database() as connection, connection.cursor() as cursor:
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 180, in _connect_to_database
    connection = psycopg2.connect(
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/venv/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgresql-k8s-primary.testing.svc.cluster.local" (10.152.183.158), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/src/charm.py", line 776, in _handle_enable_disable_extensions
    self.postgresql.enable_disable_extensions(extensions, database)
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py", line 1109, in wrapped_function
    return callable(*args, **kwargs)  # type: ignore
  File "/var/lib/juju/agents/unit-postgresql-k8s-0/charm/lib/charms/postgresql_k8s/v0/postgresql.py", line 455, in enable_disable_extensions
    raise PostgreSQLEnableDisableExtensionError() from e
charms.postgresql_k8s.v0.postgresql.PostgreSQLEnableDisableExtensionError
unit-postgresql-k8s-1: 01:47:50 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-2: 01:47:50 ERROR unit.postgresql-k8s/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-2: 01:53:42 ERROR unit.postgresql-k8s/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-1: 01:53:42 ERROR unit.postgresql-k8s/1.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata

[32mINFO    [0m pytest_operator.plugin:plugin.py:1024 Forgetting model main...