{"uid":"df05f13badccf892","name":"test_tls","fullName":"tests.integration.test_tls#test_tls","historyId":"2261d1bf845985b00a372e1561d88e5e","time":{"start":1757986323992,"stop":1757987039788,"duration":715796},"status":"failed","statusMessage":"AssertionError: TLS is not being used on pg_rewind connections\nassert 'connection authorized: user=rewind database=postgres SSL enabled' in '/var/log/postgresql/postgresql-2_0134.log:2025-09-16 01:34:00 UTC [883]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=15 LOG:  00000: statement: GRANT ALL PRIVILEGES ON DATABASE postgres TO \"rewind\";\\n/var/log/postgresql/postgresql-2_0134.log:2025-09-16 01:34:00 UTC [888]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=11 LOG:  00000: statement: GRANT \"internal_access\" TO \"rewind\";\\n/var/log/postgresql/postgresql-2_0140.log:2025-09-16 01:40:14 UTC [6047]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=9 LOG:  00000: statement: CREATE TABLE pgrewindtest (testcol INT);\\n/var/log/postgresql/postgresql-2_0140.log:2025-09-16 01:40:14 UTC [6047]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=11 LOG:  00000: AUDIT: SESSION,2,1,DDL,CREATE TABLE,TABLE,public.pgrewindtest,CREATE TABLE pgrewindtest (testcol INT);,<not logged>\\n'","statusTrace":"Traceback (most recent call last):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 344, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 246, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 850, in pytest_runtest_call\n    yield\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 900, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 263, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 178, in pytest_runtest_call\n    item.runtest()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1671, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 157, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/root/spread_project/tests/integration/test_tls.py\", line 164, in test_tls\n    for attempt in Retrying(stop=stop_after_delay(60 * 3), wait=wait_fixed(2), reraise=True):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 445, in __iter__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/root/spread_project/tests/integration/test_tls.py\", line 166, in test_tls\n    await check_tls_rewind(ops_test)\n  File \"/root/spread_project/tests/integration/test_tls.py\", line 69, in check_tls_rewind\n    assert \"connection authorized: user=rewind database=postgres SSL enabled\" in logs, (\nAssertionError: TLS is not being used on pg_rewind connections\nassert 'connection authorized: user=rewind database=postgres SSL enabled' in '/var/log/postgresql/postgresql-2_0134.log:2025-09-16 01:34:00 UTC [883]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=15 LOG:  00000: statement: GRANT ALL PRIVILEGES ON DATABASE postgres TO \"rewind\";\\n/var/log/postgresql/postgresql-2_0134.log:2025-09-16 01:34:00 UTC [888]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=11 LOG:  00000: statement: GRANT \"internal_access\" TO \"rewind\";\\n/var/log/postgresql/postgresql-2_0140.log:2025-09-16 01:40:14 UTC [6047]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=9 LOG:  00000: statement: CREATE TABLE pgrewindtest (testcol INT);\\n/var/log/postgresql/postgresql-2_0140.log:2025-09-16 01:40:14 UTC [6047]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=11 LOG:  00000: AUDIT: SESSION,2,1,DDL,CREATE TABLE,TABLE,public.pgrewindtest,CREATE TABLE pgrewindtest (testcol INT);,<not logged>\\n'","flaky":false,"newFailed":true,"newBroken":false,"newPassed":false,"retriesCount":1,"retriesStatusChange":true,"beforeStages":[{"name":"ops_test","time":{"start":1757986316522,"stop":1757986316783,"duration":261},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop","time":{"start":1757986316522,"stop":1757986316522,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"tmp_path_factory","time":{"start":1757986316522,"stop":1757986316522,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1757986323992,"stop":1757986323992,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"testStage":{"status":"failed","statusMessage":"AssertionError: TLS is not being used on pg_rewind connections\nassert 'connection authorized: user=rewind database=postgres SSL enabled' in '/var/log/postgresql/postgresql-2_0134.log:2025-09-16 01:34:00 UTC [883]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=15 LOG:  00000: statement: GRANT ALL PRIVILEGES ON DATABASE postgres TO \"rewind\";\\n/var/log/postgresql/postgresql-2_0134.log:2025-09-16 01:34:00 UTC [888]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=11 LOG:  00000: statement: GRANT \"internal_access\" TO \"rewind\";\\n/var/log/postgresql/postgresql-2_0140.log:2025-09-16 01:40:14 UTC [6047]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=9 LOG:  00000: statement: CREATE TABLE pgrewindtest (testcol INT);\\n/var/log/postgresql/postgresql-2_0140.log:2025-09-16 01:40:14 UTC [6047]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=11 LOG:  00000: AUDIT: SESSION,2,1,DDL,CREATE TABLE,TABLE,public.pgrewindtest,CREATE TABLE pgrewindtest (testcol INT);,<not logged>\\n'","statusTrace":"Traceback (most recent call last):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 344, in from_call\n    result: TResult | None = func()\n                             ^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 246, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/logging.py\", line 850, in pytest_runtest_call\n    yield\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/capture.py\", line 900, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/skipping.py\", line 263, in pytest_runtest_call\n    return (yield)\n            ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/runner.py\", line 178, in pytest_runtest_call\n    item.runtest()\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 1671, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_hooks.py\", line 512, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    raise exception\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 139, in _multicall\n    teardown.throw(exception)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 53, in run_old_style_hookwrapper\n    return result.get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_result.py\", line 103, in get_result\n    raise exc.with_traceback(tb)\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 38, in run_old_style_hookwrapper\n    res = yield\n          ^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pluggy/_callers.py\", line 121, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/_pytest/python.py\", line 157, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.12/asyncio/base_events.py\", line 687, in run_until_complete\n    return future.result()\n           ^^^^^^^^^^^^^^^\n  File \"/root/spread_project/tests/integration/test_tls.py\", line 164, in test_tls\n    for attempt in Retrying(stop=stop_after_delay(60 * 3), wait=wait_fixed(2), reraise=True):\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 445, in __iter__\n    do = self.iter(retry_state=retry_state)\n         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 378, in iter\n    result = action(retry_state)\n             ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 420, in exc_check\n    raise retry_exc.reraise()\n          ^^^^^^^^^^^^^^^^^^^\n  File \"/root/spread_project/.tox/integration/lib/python3.12/site-packages/tenacity/__init__.py\", line 187, in reraise\n    raise self.last_attempt.result()\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/concurrent/futures/_base.py\", line 449, in result\n    return self.__get_result()\n           ^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n    raise self._exception\n  File \"/root/spread_project/tests/integration/test_tls.py\", line 166, in test_tls\n    await check_tls_rewind(ops_test)\n  File \"/root/spread_project/tests/integration/test_tls.py\", line 69, in check_tls_rewind\n    assert \"connection authorized: user=rewind database=postgres SSL enabled\" in logs, (\nAssertionError: TLS is not being used on pg_rewind connections\nassert 'connection authorized: user=rewind database=postgres SSL enabled' in '/var/log/postgresql/postgresql-2_0134.log:2025-09-16 01:34:00 UTC [883]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=15 LOG:  00000: statement: GRANT ALL PRIVILEGES ON DATABASE postgres TO \"rewind\";\\n/var/log/postgresql/postgresql-2_0134.log:2025-09-16 01:34:00 UTC [888]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=11 LOG:  00000: statement: GRANT \"internal_access\" TO \"rewind\";\\n/var/log/postgresql/postgresql-2_0140.log:2025-09-16 01:40:14 UTC [6047]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=9 LOG:  00000: statement: CREATE TABLE pgrewindtest (testcol INT);\\n/var/log/postgresql/postgresql-2_0140.log:2025-09-16 01:40:14 UTC [6047]: user=operator,db=postgres,app=[unknown],client=10.1.0.152,line=11 LOG:  00000: AUDIT: SESSION,2,1,DDL,CREATE TABLE,TABLE,public.pgrewindtest,CREATE TABLE pgrewindtest (testcol INT);,<not logged>\\n'","steps":[],"attachments":[{"uid":"e0db56bdb5b90e1","name":"log","source":"e0db56bdb5b90e1.txt","type":"text/plain","size":20057}],"parameters":[],"shouldDisplayMessage":true,"stepsCount":0,"attachmentsCount":1,"hasContent":true,"attachmentStep":false},"afterStages":[{"name":"abort_on_fail::0","time":{"start":1757987039828,"stop":1757987039828,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"ops_test::finalizer","time":{"start":1757987039865,"stop":1757987040760,"duration":895},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1757987040761,"stop":1757987040761,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1757987040761,"stop":1757987040761,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1757987040761,"stop":1757987040761,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"asyncio"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_tls"},{"name":"host","value":"runnervmf4ws1"},{"name":"thread","value":"21634-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_tls"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[{"uid":"aef85676f304e27c","status":"unknown","time":{}}],"categories":[{"name":"Product defects","matchedStatuses":[]}],"history":{"statistic":{"failed":20,"broken":1,"skipped":0,"passed":353,"unknown":12,"total":386},"items":[{"uid":"3f5a17fb88ea7794","reportUrl":"../4524//#testresult/3f5a17fb88ea7794","status":"unknown","time":{}},{"uid":"5c511aa1e9142282","reportUrl":"../4521//#testresult/5c511aa1e9142282","status":"unknown","time":{}},{"uid":"dffdc96016b24a94","reportUrl":"../4520//#testresult/dffdc96016b24a94","status":"unknown","time":{}},{"uid":"522c49c6a24fea2a","reportUrl":"../4515//#testresult/522c49c6a24fea2a","status":"passed","time":{"start":1757640656886,"stop":1757641246445,"duration":589559}},{"uid":"99c070ad846f68f4","reportUrl":"../4509//#testresult/99c070ad846f68f4","status":"passed","time":{"start":1757554264776,"stop":1757554844002,"duration":579226}},{"uid":"ee9b880a8134f6d1","reportUrl":"../4500//#testresult/ee9b880a8134f6d1","status":"passed","time":{"start":1757467849936,"stop":1757468372761,"duration":522825}},{"uid":"c393939c383fc653","reportUrl":"../4489//#testresult/c393939c383fc653","status":"passed","time":{"start":1757381628712,"stop":1757382176161,"duration":547449}},{"uid":"c2ebf3c02589e5be","reportUrl":"../4488//#testresult/c2ebf3c02589e5be","status":"passed","time":{"start":1757295073610,"stop":1757295643695,"duration":570085}},{"uid":"751842ae844b916b","reportUrl":"../4486//#testresult/751842ae844b916b","status":"unknown","time":{}},{"uid":"e3b55fedad75bf86","reportUrl":"../4479//#testresult/e3b55fedad75bf86","status":"passed","time":{"start":1756949449931,"stop":1756950005442,"duration":555511}},{"uid":"a43c3b7106ba4b35","reportUrl":"../4476//#testresult/a43c3b7106ba4b35","status":"passed","time":{"start":1756863069930,"stop":1756863626299,"duration":556369}},{"uid":"a8f87be2fac3da64","reportUrl":"../4467//#testresult/a8f87be2fac3da64","status":"passed","time":{"start":1756776688697,"stop":1756777246878,"duration":558181}},{"uid":"6871bef05aa9a0c5","reportUrl":"../4466//#testresult/6871bef05aa9a0c5","status":"passed","time":{"start":1756690273752,"stop":1756690852828,"duration":579076}},{"uid":"81b6b60d06e868ea","reportUrl":"../4465//#testresult/81b6b60d06e868ea","status":"passed","time":{"start":1756603914699,"stop":1756604482813,"duration":568114}},{"uid":"6bec1a061038176c","reportUrl":"../4464//#testresult/6bec1a061038176c","status":"passed","time":{"start":1756517431781,"stop":1756518003427,"duration":571646}},{"uid":"785f2a7579cc03d9","reportUrl":"../4455//#testresult/785f2a7579cc03d9","status":"passed","time":{"start":1756431098987,"stop":1756431642267,"duration":543280}},{"uid":"ffe9fa330a637f4e","reportUrl":"../4452//#testresult/ffe9fa330a637f4e","status":"passed","time":{"start":1756344717311,"stop":1756345267968,"duration":550657}},{"uid":"5cbd65d42a0f8e65","reportUrl":"../4451//#testresult/5cbd65d42a0f8e65","status":"passed","time":{"start":1756258280565,"stop":1756258850416,"duration":569851}},{"uid":"1e0f45946ec03e1","reportUrl":"../4440//#testresult/1e0f45946ec03e1","status":"unknown","time":{}},{"uid":"56838a183f46a73","reportUrl":"../4438//#testresult/56838a183f46a73","status":"passed","time":{"start":1756085482658,"stop":1756086039506,"duration":556848}}]},"tags":["asyncio","abort_on_fail"]},"source":"df05f13badccf892.json","parameterValues":[]}