[32mINFO    [0m integration.test_trust:test_trust.py:76 Connection attempt failed: (0)
Reason: Handshake status 500 Internal Server Error -+-+- {'audit-id': 'c404b5fc-d0ee-4ba3-ac59-927a8f53b338', 'cache-control': 'no-cache, private', 'content-type': 'application/json', 'warning': '299 - "Use tokens from the TokenRequest API or manually created secret-based tokens instead of auto-generated secret-based tokens."', 'date': 'Thu, 23 Jan 2025 01:29:13 GMT', 'content-length': '169'} -+-+- b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"error dialing backend: dial tcp 10.1.0.77:10250: connect: connection refused","code":500}\n'

[32mINFO    [0m integration.test_trust:test_trust.py:78 Retrying (1/20)...
[32mINFO    [0m integration.test_trust:test_trust.py:73 Connection established: <class 'juju.client._definitions.FullStatus'>({'applications': {}, 'branches': {}, 'controller_timestamp': '2025-01-23T01:29:17.025343378Z', 'filesystems': [], 'machines': {}, 'model': <class 'juju.client._definitions.ModelStatusInfo'>({'available_version': '', 'cloud_tag': 'cloud-microk8s', 'meter_status': <class 'juju.client._definitions.MeterStatus'>({'color': '', 'message': '', 'unknown_fields': {}}), 'model_status': <class 'juju.client._definitions.DetailedStatus'>({'data': {}, 'err': None, 'info': '', 'kind': '', 'life': '', 'since': '2025-01-23T01:28:28.888684534Z', 'status': 'available', 'version': '', 'unknown_fields': {}}), 'name': 'test', 'region': 'localhost', 'sla': 'unsupported', 'type_': 'caas', 'version': '3.6.2', 'unknown_fields': {}}), 'offers': {}, 'relations': [], 'remote_applications': {}, 'storage': [], 'volumes': [], 'unknown_fields': {}})