{"uid":"4b4757e66a1912dae1a509f688f20b0f","name":"categories","children":[{"name":"Product defects","children":[{"name":"AssertionError: Unable to create continuous_writes table","children":[{"name":"test_upgrade_from_edge","uid":"e77bb7bb5a083374","parentUid":"81efe9c86a456146b55a0e93cba4cd65","status":"failed","time":{"start":1751592963458,"stop":1751593305270,"duration":341812},"flaky":false,"newFailed":true,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":true,"parameters":[],"tags":["asyncio","abort_on_fail"]}],"uid":"81efe9c86a456146b55a0e93cba4cd65"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='10.1.32.77', port=8008): Max retries exceeded with url: /cluster (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f51915f7c20>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"test_full_cluster_restart[SIGKILL-/usr/bin/patroni]","uid":"91cbd23f39da652b","parentUid":"5fece3006488edf48d75e5bbaa4f2608","status":"broken","time":{"start":1751594717458,"stop":1751594756435,"duration":38977},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":true,"retriesCount":1,"retriesStatusChange":true,"parameters":["'/usr/bin/patroni'","'SIGKILL'"],"tags":["asyncio","abort_on_fail"]}],"uid":"5fece3006488edf48d75e5bbaa4f2608"}],"uid":"bdbf199525818fae7a8651db9eafe741"}]}