[32mINFO    [0m integration.ha_tests.test_upgrade:test_upgrade.py:158 starting continuous writes to the database
[32mINFO    [0m integration.ha_tests.test_upgrade:test_upgrade.py:162 checking whether writes are increasing
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.51:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.51:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.51:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:242 Initial writes {'testing.postgresql-k8s-0': 154, 'testing.postgresql-k8s-1': 156, 'testing.postgresql-k8s-2': 157}
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.51:16443/api/v1/namespaces/testing/pods/postgresql-k8s-0 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.51:16443/api/v1/namespaces/testing/pods/postgresql-k8s-1 "HTTP/1.1 200 OK"
[32mINFO    [0m httpx:_client.py:1025 HTTP Request: GET https://10.1.0.51:16443/api/v1/namespaces/testing/pods/postgresql-k8s-2 "HTTP/1.1 200 OK"
[32mINFO    [0m integration.ha_tests.helpers:helpers.py:248 Retry writes {'testing.postgresql-k8s-0': 286, 'testing.postgresql-k8s-1': 287, 'testing.postgresql-k8s-2': 288}
[32mINFO    [0m integration.ha_tests.test_upgrade:test_upgrade.py:165 Get leader unit
[32mINFO    [0m integration.ha_tests.test_upgrade:test_upgrade.py:171 Run pre-upgrade-check action
[32mINFO    [0m integration.ha_tests.test_upgrade:test_upgrade.py:183 Inject dependency fault
[32mINFO    [0m integration.ha_tests.test_upgrade:test_upgrade.py:188 Refresh the charm
[32mINFO    [0m integration.ha_tests.test_upgrade:test_upgrade.py:191 Get first upgrading unit
[32mINFO    [0m integration.ha_tests.test_upgrade:test_upgrade.py:195 Wait for upgrade to fail on first upgrading unit
[32mINFO    [0m pytest_operator.plugin:plugin.py:936 Model status:

Model    Controller          Cloud/Region        Version  SLA          Timestamp
testing  concierge-microk8s  microk8s/localhost  3.6.4    unsupported  02:04:25Z

App                  Version  Status  Scale  Charm                Channel      Rev  Address         Exposed  Message
postgresql-k8s       14.17    active      3  postgresql-k8s                      1  10.152.183.161  no       
postgresql-test-app           active      1  postgresql-test-app  latest/edge  375  10.152.183.187  no       received database credentials of the first database

Unit                    Workload  Agent  Address      Ports  Message
postgresql-k8s/0*       active    idle   10.1.44.148         Primary
postgresql-k8s/1        active    idle   10.1.44.147         
postgresql-k8s/2        active    idle   10.1.44.146         
postgresql-test-app/0*  active    idle   10.1.44.136         received database credentials of the first database

[32mINFO    [0m pytest_operator.plugin:plugin.py:942 Juju error logs:

unit-postgresql-k8s-2: 01:43:05 ERROR unit.postgresql-k8s/2.juju-log pgdata folder not found in /var/lib/postgresql/data/pgdata
unit-postgresql-k8s-0: 01:54:07 ERROR unit.postgresql-k8s/0.juju-log charms.data_platform_libs.v0.upgrade.ClusterNotReadyError - {'message': '', 'cause': 'try to switchover manually to postgresql-k8s/0', 'resolution': ''}
unit-postgresql-k8s-0: 01:55:19 ERROR unit.postgresql-k8s/0.juju-log Cluster upgrade failed, ensure pre-upgrade checks are ran first.

[32mINFO    [0m pytest_operator.plugin:plugin.py:1024 Forgetting model main...